# Copyright (C) 2008 Vesa Karvonen
#
# This code is released under the MLton license, a BSD-style license.
# See the LICENSE file or http://mlton.org/License for details.

name := spectral-norm
args := 5500

root := ../../../../..

mlton-opts := -align 8 -loop-passes 2

include ../common.mk
