(* Copyright (C) 2007 SSH Communications Security, Helsinki, Finland
 *
 * This code is released under the MLton license, a BSD-style license.
 * See the LICENSE file or http://mlton.org/License for details.
 *)

(* WARNING: This file was generated by running 'Generate-combination.sh' script as:
 *
 *> Generate-combination.sh lib-with-default.mlb detail/generic.sml
 *)

signature Generic = sig
   include Generic ARBITRARY
end

functor MkGeneric (Arg : Generic) = struct
   structure Open = MkGeneric (Arg)
   open Arg Open
   structure ArbitraryRep = Open.Rep
end

structure Generic =
   MkGeneric (structure Open =
                 WithArbitrary (open Generic
                                structure RandomGen = RanQD1Gen)
              open Generic Open)

signature Generic = sig
   include Generic SIZE
end

functor MkGeneric (Arg : Generic) = struct
   structure Open = MkGeneric (Arg)
   open Arg Open
   structure SizeRep = Open.Rep
end

structure Generic =
   MkGeneric (structure Open = WithSize (Generic)
              open Generic Open)

signature Generic = sig
   include Generic SHRINK
end

functor MkGeneric (Arg : Generic) = struct
   structure Open = MkGeneric (Arg)
   open Arg Open
   structure ShrinkRep = Open.Rep
end

structure Generic =
   MkGeneric (structure Open = WithShrink (Generic)
              open Generic Open)

structure Generic = struct
   structure Rep = ClosePrettyWithExtra (Generic)
   open Generic Rep
end

structure UnitTest = MkUnitTest (Generic)
