# Copyright (C) 2007-2008 Vesa Karvonen
#
# This code is released under the MLton license, a BSD-style license.
# See the LICENSE file or http://mlton.org/License for details.

name := chameneos
args := @MLton fixed-heap 1.5m -- 5000000

root := ../../../../../..

mlton-opts := -loop-passes 2

include ../../common.mk
