# Copyright (C) 2008 Vesa Karvonen
#
# This code is released under the MLton license, a BSD-style license.
# See the LICENSE file or http://mlton.org/License for details.

name := ant
args := 1 5 200 200

root := ../../../../../..

mlton-opts := -align 8 -loop-passes 4

include ../../common.mk
