(* Copyright (C) 2006 SSH Communications Security, Helsinki, Finland
 *
 * MLton is released under a BSD-style license.
 * See the file MLton-LICENSE for details.
 *)

(** == Extended {WORD} modules for MLton == *)

structure Word      : WORD = MkWordExt (Word)
structure LargeWord : WORD = MkWordExt (LargeWord)
structure SysWord   : WORD = MkWordExt (SysWord)

structure Word1  : WORD = MkWordExt (Word1)
structure Word2  : WORD = MkWordExt (Word2)
structure Word3  : WORD = MkWordExt (Word3)
structure Word4  : WORD = MkWordExt (Word4)
structure Word5  : WORD = MkWordExt (Word5)
structure Word6  : WORD = MkWordExt (Word6)
structure Word7  : WORD = MkWordExt (Word7)
structure Word8  : WORD = MkWordExt (Word8)
structure Word9  : WORD = MkWordExt (Word9)
structure Word10 : WORD = MkWordExt (Word10)
structure Word11 : WORD = MkWordExt (Word11)
structure Word12 : WORD = MkWordExt (Word12)
structure Word13 : WORD = MkWordExt (Word13)
structure Word14 : WORD = MkWordExt (Word14)
structure Word15 : WORD = MkWordExt (Word15)
structure Word16 : WORD = MkWordExt (Word16)
structure Word17 : WORD = MkWordExt (Word17)
structure Word18 : WORD = MkWordExt (Word18)
structure Word19 : WORD = MkWordExt (Word19)
structure Word20 : WORD = MkWordExt (Word20)
structure Word21 : WORD = MkWordExt (Word21)
structure Word22 : WORD = MkWordExt (Word22)
structure Word23 : WORD = MkWordExt (Word23)
structure Word24 : WORD = MkWordExt (Word24)
structure Word25 : WORD = MkWordExt (Word25)
structure Word26 : WORD = MkWordExt (Word26)
structure Word27 : WORD = MkWordExt (Word27)
structure Word28 : WORD = MkWordExt (Word28)
structure Word29 : WORD = MkWordExt (Word29)
structure Word30 : WORD = MkWordExt (Word30)
structure Word31 : WORD = MkWordExt (Word31)
structure Word32 : WORD = MkWordExt (Word32)

structure Word64 : WORD = MkWordExt (Word64)
