#!/bin/bash

# Copyright (C) 2007 Vesa Karvonen
#
# This code is released under the MLton license, a BSD-style license.
# See the LICENSE file or http://mlton.org/License for details.

set -e
set -x

##########################################################################
# Configuration

prefix=/usr/include
GL=$prefix/GL
SDL=$prefix/SDL

headers="$SDL/SDL.h
$SDL/SDL_active.h
$SDL/SDL_audio.h
$SDL/SDL_cdrom.h
$SDL/SDL_copying.h
$SDL/SDL_cpuinfo.h
$SDL/SDL_endian.h
$SDL/SDL_error.h
$SDL/SDL_events.h
$SDL/SDL_getenv.h
$SDL/SDL_joystick.h
$SDL/SDL_keyboard.h
$SDL/SDL_keysym.h
$SDL/SDL_loadso.h
$SDL/SDL_main.h
$SDL/SDL_mouse.h
$SDL/SDL_mutex.h
$SDL/SDL_name.h
$GL/gl.h
$SDL/SDL_opengl.h
$SDL/SDL_platform.h
$SDL/SDL_quit.h
$SDL/SDL_rwops.h
$SDL/SDL_stdinc.h
$SDL/SDL_syswm.h
$SDL/SDL_thread.h
$SDL/SDL_timer.h
$SDL/SDL_types.h
$SDL/SDL_version.h
$SDL/SDL_video.h"

##########################################################################
# MLton Platform

arch="$(mlton -show path-map | awk '/^TARGET_ARCH/ {print $2}')"
os="$(mlton -show path-map | awk '/^TARGET_OS/ {print $2}')"
target="$arch-$os"
outdir=generated/$target

mkdir -p $outdir

##########################################################################
# Generate ML-NLFFI

mlnlffigen -linkage static                             \
           -dir $outdir                                \
           -cppopt "-include detail/config/$target.h"  \
           $headers

##########################################################################
# Generate #define constants

consts=$outdir/constants.sml

echo "(* WARNING: Generated by the $(basename $0) script. *)

local
   open IntInf
   infix orb
in
   (* Manually translated: *)
   fun SDL_BUTTON i = IntInf.<< (1, Word.fromLargeInt (i-1))" > $consts

for header in $headers ; do
    echo "" >> $consts
    echo "   (* From $header: *)" >> $consts
    sed -e 's#/\*.*\*/##g' -e $'s#[\t]\\+$##g' $header                                              \
     | grep -o -e $'^#define[\t ]\\+\\(GL\\|SDL\\)_[_a-zA-Z0-9]\\+[\t ]\\+[^\\\\g-w]\\+$'           \
     | sed -e $'s-#define[\t ]\\+\\([^\t ]\\+\\)[\t ]\\+\\(.\\+\\)-   val \\1 : IntInf.int = \\2-g' \
           -e 's#|# orb #g'                                                                         \
           -e 's#~# notb #g'                                                                        \
           -e 's#-#~#g'                                                                             \
           -e 's#(size_t)##g'                                                                       \
           -e 's#(Uint32)##g'                                                                       \
     >> $consts
done

echo 'end' >> $consts
